services:
  sshnake:
    image: marcelaritonang/sshnake:latest
    container_name: sshnake
    ports:
      - "2222:2222"
    restart: unless-stopped
    pull_policy: always
    networks:
      - internet

networks:
  internet:
    external: true
    name: internet
